export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_RECIEVE = 'AUTH_RECIEVE';
export const API_REQUEST = 'API_REQUEST';
export const ALL_NEWS_RECIEVE = 'ALL_NEWS_RECIEVE';
export const NEWS_RECIEVE = 'NEWS_RECIEVE';
